{% set version = '0.3.4' %}

package:
  name: flask-ldap-login
  version: {{ version }}

build:
  entry_points:
    - flask-ldap-login-check = flask_ldap_login.check:main

requirements:
  build:
    - python
    - setuptools
    - python-ldap       # required b/c of setuptools
    - flask             # required b/c of setuptools
    - flask-wtf >=0.9.0 # required b/c of setuptools

  run:
    - python
    - python-ldap
    - flask
    - flask-wtf >=0.9.0  
    - wtforms >=2.0.0   # transitive dependency, but flask-wtf won't work with old versions

test:
  imports:
    - examples
    - flask_ldap_login

  commands:
    - flask-ldap-login-check --help

about:
  home: https://github.com/ContinuumIO/flask-ldap-login
  license: BSD
  summary: 'Flask ldap login is designed to work on top of an existing application.'
